# Generated by Django 2.2 on 2020-11-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201110_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'product image', 'verbose_name_plural': 'product images'},
        ),
    ]
