# Generated by Django 3.0.8 on 2020-11-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catrgory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_product'),
        ),
    ]
