# Generated by Django 3.0.8 on 2020-11-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201111_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='codition',
            new_name='condition',
        ),
    ]
